apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: api
bases:
  - ../.template/api
resources:
  - ingress.yaml
images:
  - name: <template>
    newName: jsoliveira/api-services-calculator
    newTag: latest-test
commonLabels:
  name: calculator
replacements:
  - source:
      kind: Deployment
      fieldPath: metadata.labels.name
    targets:
      - select:
          kind: Deployment
        fieldPaths:
          - metadata.name
          - spec.selector.matchLabels.app
          - spec.template.metadata.labels.app
      - select:
          kind: Service
        fieldPaths:
          - metadata.name
          - spec.selector.app
