apiVersion: apps/v1
kind: Deployment
metadata:
  name: <template>
spec:
  selector:
    matchLabels:
      app: <template>
  template:
    metadata:
      labels:
        app: <template>
    spec:
      containers:
      - name: app
        image: <template>
        imagePullPolicy: Always
        resources:
          limits:
            memory: "50Mi"
            cpu: "100m"
        livenessProbe:
           tcpSocket:
              port: 80
        readinessProbe:
           tcpSocket:
              port: 80
        ports:
        - containerPort: 80
